GET http://localhost:3000/transaction?page=1&limit=3
Content-Type: application/json
Authorization: Bearer yJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Impvc2Vtb3JhbGVzd2F0YW5hYmUyMEBnbWFpbC5jb20iLCJpYXQiOjE3MjE4MjkzNTcsImV4cCI6MTcyMjQzNDE1N30.aF1N7uwSofmCeMNznN1xuZDdh8zqZCcMPiBhf5XdqeA