GET http://localhost:3000/transaction?page=1&limit=10
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Impvc2Vtb3JhbGVzd2F0YW5hYmUyMEBnbWFpbC5jb20iLCJpYXQiOjE3MjE4Mjk5NDAsImV4cCI6MTcyMjQzNDc0MH0.qlFlcspETHrT-zkhgusuoS4tRFED2wm1bChUZroeofA