version: '3.8'

services:
  nestjs-app:
    image: node:18
    container_name: nestjs-app
    working_dir: /app
    volumes:
      - ./:/app
    command: sh -c "yarn install && npm run start:dev"
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/nestjs
      - APP_PORT=3000
      - TOKEN_PROVIDER_EXPIRATION_PERIOD=7d
      - PASSWORD_ENCRYPTION_ROUNDS=12
      - TOKEN_PROVIDER_SECRET=spiderman
      - EMAIL_HOST=sandbox.smtp.mailtrap.io
      - EMAIL_USERNAME=86ec9c2fa95a4e
      - EMAIL_PASSWORD=f7a66e0e0dfe84
      - CAMBIO_SEGURO_API_URL=https://api.test.cambioseguro.com/api/v1.1

  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: