GET http://localhost:3000/transaction/66a0011740c32bfee221867f
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Impvc2Vtb3JhbGVzd2F0YW5hYmVAZ21haWwuY29tIiwiaWF0IjoxNzIxNzYxMjMzLCJleHAiOjE3MjIzNjYwMzN9.qDGZtwddIl6RFszYeYNpS8LII8_97dq023eiU--KREE